# Writes a build stamp header. Run as a pre-build step on every build, not at configure
# time, so the stamp is the moment the binary was actually produced.
#
# Only rewrites the file when the contents change - an unconditional write would make
# everything that includes it recompile on every build even when nothing moved.

string(TIMESTAMP stamp "%Y-%m-%d %H:%M:%S")
set(content "#pragma once\n\n// Generated by cmake/WriteBuildStamp.cmake - do not edit.\nnamespace windowmark::app {\ninline constexpr wchar_t kBuildStamp[] = L\"${stamp}\";\n}\n")

set(existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
